### ISSUE TITLE
Simplify API function parameters

### ISSUE THREAD

**Issue by edisonchee** [yuhong90/node-google-calendar#2]
Right now using a method requires supplying parameters in order, e.g.
```javascript
// function declaration
function insertEvent(calendarId, eventSummary, startDateTime, endDateTime, location, status, description, colour) { ... };
// actual usage
insertEvent('primary', null, ................);
```

```javascript
// function declaration
function insertEvent(event) {
  // reject if required parameters are not present
  // e.g. if (!event.start) throw new Error('Start time missing');

  // plug event directly into request body
};
// actual usage
let event1 = {
  summary: 'Event 1',
  start: {
    dateTime: '2015-05-28T09:00:00-07:00'
  },
  end: {
    dateTime: '2015-05-28T17:00:00-07:00'
  }
};

let event2 = {
  calendarId: 'primary',
  eventSummary: 'Event 2',
  description: 'I can add descriptions if I want to',
  start: {
    dateTime: '2015-05-28T09:00:00-07:00'
  },
  end: {
    dateTime: '2015-05-28T17:00:00-07:00'
  }
};

insertEvent(event1);
insertEvent(event2);
```

Users can refer to Google's [documentation](https://developers.google.com/google-apps/calendar/v3/reference/events/insert) on what parameters to supply, and choose to include or exclude parameters.

**Comment by cjcheshire** [comment]
Yea, I just ran into this.  I want to set the All day flag using originalStartTime.date but can't :(

**Comment by cjcheshire** [comment]
I've put in a PR to support this:
https://github.com/yuhong90/node-google-calendar/pull/4

To not break the existing library api there is an additionalOptions object you can pass. This will be merged with the current event object passed to google.

**Comment by yuhong90** [comment]
Done in the v1.0.0.
