### ISSUE TITLE
Cant view events on google calendar 

### ISSUE THREAD

**Issue by iTechKnow** [yuhong90/node-google-calendar#5]
I'm unable to insert a google calendar event as it returns me a 404 error. Here is my code:

```
 insertEvent(calendarIdList['calendar-1'], 'TestEventName', '2017-05-20T12:00:00+08:00', '2017-05-20T15:00:00+08:00', 'location', 'confirmed', 'some description here');

function insertEvent(calendarId, eventSummary, startDateTime, endDateTime, location, status, description) {
	let event = {
		'start': {
			'dateTime': startDateTime
		},
		'end': {
			'dateTime': endDateTime
		},
		'location': location,
		'summary': eventSummary,
		'status': status,
		'description': description,
		'colorId': 1
	};

	cal.Events.insert(calendarId, event)
		.then(resp => {
			let json = resp;
			let results = {
				id: json.id,
				'summary': json.summary,
				'location': json.location,
				'status': json.status,
				'htmlLink': CALENDAR_URL,
				'start': json.start.dateTime,
				'end': json.end.dateTime,
				'created': new Date(json.created)
			};
			console.log('inserted event:');
			console.log(results);
		})
		.catch(err => {
			console.log('Error: insertEvent-' + err);
		});
}
```
This is the settings file for calendar_id
```
const CALENDAR_ID = {
	'primary': '',
	'calendar-1': 'xxxxxx@group.calendar.google.com'
};

```
Then when I go to my calendar and make it public, it returns me a 403 error response "forbidden"

EDIT: It was because I didnt share the calendar with my googles service account.

I am now able to get this working, phew...

**Comment by yuhong90** [comment]
Hello there!

#### Granting permission to Google Calendar
Yupe, specific permission must be given to the created Service Account for each of the calendars that your application want to have access to make changes / read events. Probably why you encountered the 403!

Also, you're right. The calendar must be public for this to work.
 
#### Setting up config file & using the config file
Within the settings file, `CALENDAR_ID` should specify the calendar IDs of each calendar that the service account has been granted access to.  (To get the IDs of each of the calendar, go to calendar's settings page > _"Calendar Details"_ tab > under _"Calendar Address"_ section > Calendar ID.)

For example:

```javascript
// settings.js
const CALENDAR_ID = {
	'primary': '<your main calendar id>@gmail.com' //setup config with my main calendar's id
};
module.exports.calendarId = CALENDAR_ID;
```

```javascript
// using config calendar id within your app
const calendarId = require('../config/Settings').calendarId;
...
cal.Events.insert(calendarId['primary'], params);
...
```

Hope this helps. I've updated the wiki instructions on this setup too.

**Comment by cfjedimaster** [comment]
Query - must we make the calendar public? Sharing it with the service account makes sense.
