### ISSUE TITLE
Error when inserting event with JSON key

### ISSUE THREAD

**Issue by mycaule** [yuhong90/node-google-calendar#9]
Hello, 

I get this error from Calendar API when trying to insert with your library with the code sample provided in the README file.
```
insertEvent-Error: {"origin":"Events.insert","error":"options.email is required"}
```

What fields do I need to add ?
https://developers.google.com/google-apps/calendar/v3/reference/events/insert

Node version : v6.11.1

The error probably comes from the `google-auth-jwt` package
https://github.com/extrabacon/google-oauth-jwt/blob/master/lib/auth.js#L81

Maybe you need to add `email` field in the JWT Authentication part of your package.
I used the json key method

**Comment by yuhong90** [comment]
hi,

Can you share how you installed the package, your settings config and how you ran the sample code? I'm thinking it could be a setup issue.

**Comment by mycaule** [comment]
```
const CalendarAPI = require('node-google-calendar');
let key = require('./project-xxxxxxxxxxxx.json').private_key;

let config = {
  serviceAccId: 'project-nnnnnn@appspot.gserviceaccount.com',
  keyFile: key,
  timezone: 'UTC+01:00',
  calendarId: {
    'dummy': 'xxxxxxxxxxxxxxxxxxxxxxxxx@group.calendar.google.com'
  }
};

let cal = new CalendarAPI(config);

let insert = (start, end) => {
  let params = {
    start: { dateTime: '2017-10-12T07:00:00+01:00' },
    end: { dateTime: '2017-10-12T08:00:00+01:00' },
    location: 'Coffeeshop',
    summary: 'Breakfast',
    status: 'confirmed',
    description: '',
    colorId: 1,
    options: {
      email: 'username@gmail.com'
    }
  };

  return cal.Events.insert(config.calendarId.dummy, params);
};

insert('start', 'end')
  .then(resp => {
     console.log('inserted event:');
     console.log(resp);
     res.json(result);
  })
.catch(err => {
     console.log('Error: insertEvent-' + err);
     res.json(result);
   });
```

**Comment by yuhong90** [comment]
The 'options.email' property that you specified in the request body is not a supported property of [events.insert](https://developers.google.com/google-apps/calendar/v3/reference/events/insert) . You can try out the API explorer provided when figuring out the supported properties.

Try removing it or use something like the following to insert an event into your calendar.

```
let params = {
	'summary': 'Sample Event',
	'start': { 'dateTime': '2017-10-18T21:00:00+08:00' },
	'end': { 'dateTime': '2017-10-18T22:00:00+08:00' },
	'description': '',
        'location: 'Coffeeshop',
	'status': 'confirmed',
	'colorId': 1,
	'attendees': [ { 'email': 'xxxxx@gmail.com' } ]
};
let optionalQueryParams = {
	sendNotifications: true
};

return cal.Events.insert(calendarId, params, optionalQueryParams)
	.then(resp => {
		console.log(resp);
	})
	.catch(err => {
		console.log('Error: insertEvent', err.message);
	});
```

Let me know if you're still having problems with this :)

**Comment by mycaule** [comment]
Still have the error while removing the field. I tried adding `options.email` to solve the original problem.

**Comment by AmitMY** [comment]
I am getting the same error.
If I run the code locally it adds an event with no problem, but if I run it using firebase cloud functions, the error happens.

This is my event:
```
const event = {
  start: { 'dateTime': start.toISOString() },
  end: { 'dateTime': end.toISOString() },
  summary: title,
  status: 'confirmed',
  description: ''
};
```

**Comment by AmitMY** [comment]
For me, the issue was that I used an unescaped JSON key in the config file, so firebase config just skipped the `serviceAcctId` parameter I set.

**Comment by yuhong90** [comment]
Its rather unlikely that email field needs to be added into JWT since its working okay on my setup.

@mycaule, could it be a similar issue as @AmitMY mentioned - related to how your json key is read?

**Comment by mycaule** [comment]
Yeah I tried the code on Google Cloud Functions too.

**Comment by AmitMY** [comment]
@mycaule So what I suggest is you instead of include the JSON key in cloud config, first escape the key itself (`\n` is bad there), and when getting that in code unescape it.
Use either `escape`/`unescape` or `encodeURIComponent`/`decode...`

**Comment by mdmasumbillah** [comment]
I can not insert event and show this error,

Error: insertEvent-{"origin":"Events.insert","error":{"statusCode":"403(Forbidden)","errorBody":{"error":{"errors":[{"domain":"global","reason":"forbidden","message":"Forbidden"}],"code":403,"message":"Forbidden"}}}}
